### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by mcfilmmakers** [hoglet67/Atomulator#4]
I'd love to use atomulator from my front end but I can't seem to be able to launch it in fullscreen or preload a game in the tape or disk slot. These features are essential for any emulator.

Also, a way to have fullscreen without the menu bar showing would be amazing.

**Comment by keesvanoss** [comment]
You can create a shortcut to start Atomulator and set the window property of the shortcut to fullscreen.

The best way is to install the Acorn Atom Software Archive at: https://github.com/hoglet67/AtomSoftwareArchive/releases/tag/V11
Unpack the zip in the Atomulator\MMC directory

Then start Atomulator, type *CFG 80 and close Atomulator.
When you call the shortcut now, Atomulator starts in fullscreen with a menu to run almost 1000 programs.
To reset the Atom with break, press SHIFT-BREAK.

**Comment by mcfilmmakers** [comment]
Thank you for suggesting the shortcut method, but it really should be a native option.

The  Acorn Atom Software Archive is a terrible solution for frontends. Each game is already separate in the frontend. Clicking the game should launch that specific game only and you can't do that and it is a problem unique to Atomulator.

**Comment by hoglet67** [comment]
> The Acorn Atom Software Archive is a terrible solution for frontends

The Atom Software Archive exists primarily for real Atoms fitted with the AtoMMC system.

Atomulator, just happens to allow this configuration to be emulated.

When you say  "Each game is already separate in the frontend", what front-end are you referring to.

Sorry, I'm lacking a but of contexts as to what environment you are trying to run Atomulator in....

By the way, I do agree with you that additional command line options would be useful, allowing a single tape or disk image to be pre-loaded.

Dave

**Comment by Mr-Ugly-Hacks** [comment]
On the Linux version at least I was able to load a tape at start like this ./Atomulator -tape filename.uef
and for disk ./Atomulator -disc filename.dsk

I just decided to try the command line options that were available for the b-em emulator and got lucky.

**Comment by hoglet67** [comment]
The currently supported options are:
```
-disc disc.ssd  - load disc.ssd into drives :0/:2
-disc1 disc.ssd - load disc.ssd into drives :1/:3
-tape tape.uef  - load tape.uef
-fasttape       - set tape speed to fast
-autoboot       - cause atommc to auto boot on power on reset
-debug          - start debugger
```
(--help should list these)

See:
https://github.com/hoglet67/Atomulator/blob/master/src/atom.c#L156

**Comment by mcfilmmakers** [comment]
> The currently supported options are:
> 
> ```
> -disc disc.ssd  - load disc.ssd into drives :0/:2
> -disc1 disc.ssd - load disc.ssd into drives :1/:3
> -tape tape.uef  - load tape.uef
> -fasttape       - set tape speed to fast
> -autoboot       - cause atommc to auto boot on power on reset
> -debug          - start debugger
> ```
> 
> (--help should list these)
> 
> See:
> https://github.com/hoglet67/Atomulator/blob/master/src/atom.c#L156

THIS is what I need! Thank you! However, I should point out that this should seriously be pointed out in the readme. It simply isn't there.

Is there no command to launch in fullscreen?

**Comment by hoglet67** [comment]
> However, I should point out that this should seriously be pointed out in the readme. It simply isn't there.

Pull requests are always welcome.

It is an open source project after all...

> Is there no command to launch in fullscreen?

Not currently.

Dave

**Comment by hoglet67** [comment]
Added #6 and #7
